spring.application.name=video-call-web-app

server.port=8080


springdoc.swagger-ui.title=Video Call API Documentation
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

springdoc.info.title=Video Call API
springdoc.info.version=v1.0.0
springdoc.info.description=Tài liệu REST API cho ứng dụng Video Call (Backend)

server.forward-headers-strategy=framework
