# =============================================================================
# CONFIG: Giống VM nhưng tách TCP và UDP
# =============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-config
  namespace: video-call-prod
data:
  livekit.yaml: |
    port: 7880
    
    rtc:
      port_range_start: 50000
      port_range_end: 50100
      use_external_ip: true
      udp_port: 7882
      tcp_port: 7881
    
    redis:
      address: redis:6379
    
    keys:
      devkey: my_super_secure_secret_key_for_dev_only_123
    
    logging:
      level: info
    
    webhook:
      urls:
        - "https://lkht.id.vn/api/webhook/livekit"
      api_key: "devkey"

---
# =============================================================================
# SERVICE 1: TCP ONLY (HTTP + TURN TCP)
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: livekit-tcp
  namespace: video-call-prod
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  
  selector:
    app: livekit
  
  ports:
    # HTTP API + WebSocket
    - name: http
      port: 7880
      targetPort: 7880
      protocol: TCP
    
    # TURN TCP
    - name: turn-tcp
      port: 7881
      targetPort: 7881
      protocol: TCP

---
# =============================================================================
# SERVICE 2: UDP ONLY (TURN UDP + WebRTC Media)
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: livekit-udp
  namespace: video-call-prod
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  
  selector:
    app: livekit
  
  ports:
    # TURN UDP
    - name: turn-udp
      port: 7882
      targetPort: 7882
      protocol: UDP
    
    # WebRTC Media Ports (chỉ expose 1 số port đại diện)
    # LiveKit sẽ tự động sử dụng các port trong range 50000-50100
    - name: rtc-50000
      port: 50000
      targetPort: 50000
      protocol: UDP
    - name: rtc-50010
      port: 50010
      targetPort: 50010
      protocol: UDP
    - name: rtc-50020
      port: 50020
      targetPort: 50020
      protocol: UDP
    - name: rtc-50030
      port: 50030
      targetPort: 50030
      protocol: UDP
    - name: rtc-50040
      port: 50040
      targetPort: 50040
      protocol: UDP
    - name: rtc-50050
      port: 50050
      targetPort: 50050
      protocol: UDP
    - name: rtc-50060
      port: 50060
      targetPort: 50060
      protocol: UDP
    - name: rtc-50070
      port: 50070
      targetPort: 50070
      protocol: UDP
    - name: rtc-50080
      port: 50080
      targetPort: 50080
      protocol: UDP
    - name: rtc-50090
      port: 50090
      targetPort: 50090
      protocol: UDP
    - name: rtc-50100
      port: 50100
      targetPort: 50100
      protocol: UDP

---
# =============================================================================
# DEPLOYMENT: Giống VM
# =============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit
  namespace: video-call-prod
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: livekit
  
  template:
    metadata:
      labels:
        app: livekit
    
    spec:
      containers:
        - name: livekit
          image: livekit/livekit-server:latest
          
          command: ["/livekit-server"]
          args:
            - "--config"
            - "/etc/livekit.yaml"
          
          ports:
            - name: http
              containerPort: 7880
              protocol: TCP
            - name: turn-tcp
              containerPort: 7881
              protocol: TCP
            - name: turn-udp
              containerPort: 7882
              protocol: UDP
            - name: rtc-start
              containerPort: 50000
              protocol: UDP
            - name: rtc-end
              containerPort: 50100
              protocol: UDP
          
          volumeMounts:
            - name: config
              mountPath: /etc/livekit.yaml
              subPath: livekit.yaml
          
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          
          livenessProbe:
            httpGet:
              path: /
              port: 7880
            initialDelaySeconds: 30
            periodSeconds: 10
          
          readinessProbe:
            httpGet:
              path: /
              port: 7880
            initialDelaySeconds: 10
            periodSeconds: 5
      
      volumes:
        - name: config
          configMap:
            name: livekit-config